apiVersion: v1
kind: Service
metadata:
  name: pgsql-idc-solicitud
  labels:
     app: db-solicitud
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30036
    protocol: TCP
  selector:
     app: db-solicitud
