apiVersion: apps/v1 # i se Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: idc-servicio-formularios
  labels:
    estado: "1"
spec:
  selector:   #permite seleccionar un conjunto de objetos que cumplan las condicione
    matchLabels:
      app: formularios
  replicas: 1
  strategy:
    type: RollingUpdate
  template:   # Plantilla que define el container
    metadata:
      labels:
        app: formularios
    spec:
      containers:
      - name: idc-servicio-formularios
        image: dmcontainerregister.azurecr.io/idc-servicio-formularios:latest
        ports:
          - containerPort: 8504
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s-dev
          - name: SERVER_PORT
            value: "8504"
      imagePullSecrets:
        - name: regcred
