apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8-idc-diagnostico
  labels:
    app: db-diagnostico
    type: db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db-diagnostico
      type: db
  template:
    metadata:
      labels:
        app: db-diagnostico
        type: db
    spec:
      containers:
        - name: mysql8-idc-diagnostico
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: db_idc_diagnostico
            - name: MYSQL_ROOT_PASSWORD
              value: Carvajal2019*
      nodeSelector:
        nodo: master
