apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8-idc-estaciones
  labels:
    app: db-estaciones
    type: db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db-estaciones
      type: db
  template:
    metadata:
      labels:
        app: db-estaciones
        type: db
    spec:
      containers:
        - name: mysql8-idc-estaciones
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: db_idc_estaciones
            - name: MYSQL_ROOT_PASSWORD
              value: Carvajal2019*
