apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
     app: apache
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
     app: apache
