apiVersion: v1
kind: Service
metadata:
  name: pgsql12-idc-inscripcion
  labels:
     app: db-inscripciones
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30032
    protocol: TCP
  selector:
     app: db-inscripciones
